# Generated by Django 5.2.8 on 2025-11-19 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSplit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_samples', models.IntegerField()),
                ('train_samples', models.IntegerField()),
                ('val_samples', models.IntegerField()),
                ('test_samples', models.IntegerField()),
                ('stratify_column', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
